- hosts: all
  vars_files:
  - vars.yaml

  tasks:
  - name: Init swarm
    shell: |
         docker swarm init
         /bin/true
  - name: Create and start services
    shell: |
         docker stack deploy --compose-file {{ stage_dir }}/docker-compose.yaml goapi
    register: output
    args:
      executable: /bin/bash

  - name: Check status
    shell: |
           docker stack ps goapi
    register: output 
    args:
      executable: /bin/bash
    changed_when: False

  - debug: msg={{ output.stdout.split('\n') }}
