[tool.poetry]
name = "go-fastapi"
version = "0.1.0"
description = ""
authors = ["Sierra Taylor Moxon <sierra.taylor@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.77.1"
Flask = "^2.1.2"
uvicorn = "^0.17.6"
python-multipart = "^0.0.5"
Jinja2 = "^3.1.2"
ontobio = "^2.8.2"
biothings-client = "^0.2.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
