[tool.poetry]
version = "0.1.0"
description = ""
authors = ["Sierra Taylor Moxon <sierra.taylor@gmail.com>"]
name = "app"


[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.92.0"
uvicorn = "^0.20.0"
python-multipart = "^0.0.5"
ontobio = "^2.8.3"
biothings-client = "^0.2.6"
gunicorn = "^20.1.0"
pytest-bdd = "^6.1.1"
prefixcommons = "^0.1.12"
Sphinx = "^5.0.2"
sphinx-rtd-theme = "^1.2.0"
sphinxcontrib-napoleon = "^0.7"
tox = "^4.4.5"
mypy = "^1.0.0"
pyroma = "^4.1"
httpx = "^0.23.3"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
    "tests/unit",
    "tests/integration",
    "tests/ingetration/step_defs",
]

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-mermaid"]
