[tool.poetry]
name = "go-fastapi"
version = "0.1.0"
description = ""
authors = ["Sierra Taylor Moxon <sierra.taylor@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.79.0"
uvicorn = "^0.17.6"
python-multipart = "^0.0.5"
ontobio = "^2.8.3"
biothings-client = "^0.2.6"
gunicorn = "^20.1.0"
pytest-bdd = "^6.0.1"
prefixcommons = "0.1.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
    "tests/unit",
    "tests/integration",
    "tests/ingetration/step_defs",
]

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-mermaid"]
