solr_url:
  url: "https://golr-aux.geneontology.io/solr/"
  timeout: 30
ontologies:
  - id: go
    handle: go
    pre_load: false
sparql_url:
  url: "http://rdf.geneontology.org/sparql"
  timeout: 60
